FIXUP: FROMLIST: drm/i915/pxp: Create the arbitrary session after boot
0-day says:

drivers/gpu/drm/i915/pxp/intel_pxp_arb.c:68:5: error:
	no previous prototype for function 'intel_pxp_arb_reserve_session'

Since the function is only used locally, make it static.

BUG=b:155511178
TEST=Compile

Change-Id: I351b4c348d8489024de1c56beaefbb8aaa8b7d43
Disallow-Recycled-Builds: test-failures
Reported-by: kernel test robot <lkp@intel.com>
Signed-off-by: Guenter Roeck <groeck@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/kernel/+/2605812
Reviewed-by: Sean Paul <seanpaul@chromium.org>