UPSTREAM: mt76: mt7615: fix potential overflow on large shift
Fix the following static checker warning:
error: undefined (user controlled) shift '(((1))) << (c->omac_idx)'

Fixes: 402a695b1ae6 ("mt76: mt7615: fix CSA notification for DBDC")
Reported-by: Dan Carpenter <dan.carpenter@oracle.com>
Signed-off-by: Ryder Lee <ryder.lee@mediatek.com>
Signed-off-by: Felix Fietkau <nbd@nbd.name>
(cherry picked from commit 3253f8fddd954aba9ac88ce3c34551dcca505b21)

BUG=b:178754244
TEST=build and boot on asurada

Signed-off-by: Linux Patches Robot <linux-patches-robot@chromeos-missing-patches.google.com.iam.gserviceaccount.com>
Change-Id: Idb027c6dc3a1953eb238c70126ca294440b88cb6
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/kernel/+/3007371
Reviewed-by: Sean Paul <seanpaul@chromium.org>
Reviewed-by: Yen-lin Lai <yenlinlai@chromium.org>
Commit-Queue: Joshua Emele <jemele@chromium.org>
Tested-by: Joshua Emele <jemele@chromium.org>