FIXUP: FROMLIST: sched/core: Sync the min_vruntime of cores when the system enters force-idle
0-day reports:

kernel/sched/fair.c:463:30: error: unused function 'core_cfs_rq'

The use of this function was removed with commit 6eea2668b028 ("FROMLIST:
sched/core: Sync the min_vruntime of cores when the system enters
force-idle"), but the function was left behind.

BUG=b:166194367
TEST=ARC Audio tests

Change-Id: I6c83df842986c65e35588af4e35748b8376682d7
Disallow-Recycled-Builds: test-failures
Signed-off-by: Guenter Roeck <groeck@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/kernel/+/2577657
Commit-Queue: Joel Fernandes <joelaf@google.com>
Reviewed-by: Joel Fernandes <joelaf@google.com>
Tested-by: Joel Fernandes <joelaf@google.com>