FIXUP: ANDROID: Initial commit of Incremental FS
fs/incfs/vfs.c: In function 'incfs_mount_fs':
include/linux/compiler.h:350:38: error: call to '__compiletime_assert_154'
	declared with attribute error: BUILD_BUG_ON failed: PAGE_SIZE != INCFS_DATA_FILE_BLOCK_SIZE

INCFS_DATA_FILE_BLOCK_SIZE is set to 4096. We know that PAGE_SIZE on x86
is fixed to 4096. Page size on arm64 is configurable. Other architectures
are more tricky. Limit builds to x86 and arm64 builds with the appropriate
page size. Others can be added later as needed and supported.

BUG=b/133435829
TEST=Build and observe warnings

Disallow-Recycled-Builds: test-failures
Change-Id: Ifbb0e78ac38ef6fe52322f51b4e16e28f943bed5
Reported-by: kernel test robot <lkp@intel.com>
Signed-off-by: Guenter Roeck <groeck@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/kernel/+/2424045
Reviewed-by: Oleksandr Peletskyi <peletskyi@google.com>