FIXUP: CHROMIUM: mm: per-process reclaim
0-day reports:

h8300-linux-ld: fs/proc/base.o:(.rodata+0x838):
	undefined reference to `proc_reclaim_operations'

This is seen if MMU is disabled and PROCESS_RECLAIM is enabled.
proc_reclaim_operations() is only compiled if both MMU and
PROCESS_RECLAIM are enabled, meaning that PROCESS_RECLAIM really
depends on MMU. Add the missing dependency.

While at it, remove the unnecessary "default n".

BUG=chromium:973963
TEST=0-day build test passes

Change-Id: Iaa0108eae7702a8466cc6eef7ac4d036d071afe2
Reported-by: kernel test robot <lkp@intel.com>
Signed-off-by: Guenter Roeck <groeck@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/kernel/+/2368767
Reviewed-by: Sonny Rao <sonnyrao@chromium.org>