FIXUP: FROMLIST: platform/chrome: wilco_ec: Add keyboard backlight LED support
If LEDS_CLASS is not enabled, we get:

ld: drivers/platform/chrome/wilco_ec/keyboard_leds.o:
	in function `wilco_keyboard_leds_init':
drivers/platform/chrome/wilco_ec/keyboard_leds.c:190:
	undefined reference to `devm_of_led_classdev_register'

as reported by 0-day. Since LED support is built into the core wilco_ec
driver, it now depends on LEDS_CLASS. Add the missing dependency.

Note: It is an open question if the LED driver should instead be an
independent module. This fix explicitly does not address that question.

BUG=b:141952530
TEST=Build images with LEDS_CLASS disabled and enabled

Change-Id: I185b862ab65f89d0cf67516c8335d1dcb3ed7d7b
Reported-by: kbuild test robot <lkp@intel.com>
Signed-off-by: Guenter Roeck <groeck@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/kernel/+/1901532
Reviewed-by: Daniel Campello <campello@chromium.org>
(cherry picked from commit 92452e91e038ff6b6e2ce222f0f2a7163150a953)
Signed-off-by: Guenter Roeck <groeck@chromium.org>