FIXUP: BACKPORT: io_uring: replace workqueue usage with io-wq
Commit b75748e5171e ("BACKPORT: io_uring: replace workqueue usage with
io-wq") removed a call to revert_creds(old_cred) from io_wq_submit_work().
However, old_cred is still assigned but not used. This results in wide-spread
build warnings/errors depending on the configuration, as reported by 0-day.

fs/io_uring.c:2157:21: error: variable 'old_cred' set but not used
fs/io_uring.c:2157:21: warning: variable 'old_cred' set but not used

This in turn results in error obfuscation: The widely reported warning/error
drowns potential real problems in noise. Remove the unused variable to
fix the warning.

The code itself looks suspicious. However, removing the now unused variable
and assignment at least makes the code compile without warnings, and it does
not introduce a functional change.

BUG=chromium:901139
TEST=run crosvm with virtio-blk device using io_uring (CL:2306786)

Change-Id: I57a16e521806c641ece2b95f455ff8c5ba9a75a6
Disallow-Recycled-Builds: test-failures
Signed-off-by: Guenter Roeck <groeck@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/kernel/+/2668182
Reviewed-by: Dylan Reid <dgreid@chromium.org>