FROMGIT: media: venus: fix build on 32bit environments
As reported by jenkins@linuxtv.org, the build with i386 fails
with:

	ld: drivers/media/platform/qcom/venus/helpers.o: in function `venus_helper_load_scale_clocks':
	(.text+0x1d77): undefined reference to `__udivdi3'
	ld: (.text+0x1dce): undefined reference to `__udivdi3'
	make: *** [Makefile:1094: vmlinux] Error 1

That's because it divides an u32 bit integer by a u64 one.

BUG=b:79450911
TEST=Kernel builds and boots for Cheza.

Reviewed-by: Stanimir Varbanov <stanimir.varbanov@linaro.org>
Signed-off-by: Mauro Carvalho Chehab <mchehab+samsung@kernel.org>
(cherry picked from commit 219031a6e7dff52a066e8b074adc0697f501e3d3
 git://linuxtv.org/media_tree.git master)
Signed-off-by: Alexandre Courbot <acourbot@chromium.org>

Change-Id: I8857af9a38a145760e7e2469d556177ae980d405
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/kernel/+/1871537
Tested-by: Alexandre Courbot <acourbot@chromium.org>
Auto-Submit: Alexandre Courbot <acourbot@chromium.org>
Commit-Queue: Tomasz Figa <tfiga@chromium.org>
Reviewed-by: Tomasz Figa <tfiga@chromium.org>
Reviewed-by: Sean Paul <seanpaul@chromium.org>