FIXUP: CHROMIUM: drm/bridge: anx7625: Add anx7625 port switching.
0-day reports:

anx7625.c:(.text+0x38): undefined reference to `typec_mux_unregister'
anx7625.c:(.text+0xd14): undefined reference to `typec_mux_get_drvdata'
anx7625.c:(.text+0x1c38): undefined reference to `typec_mux_register'

The driver now depends on TYPEC.

BUG=b:149658764
TEST=build

Change-Id: I7d68af091bb13c35ca5030e6ef4413163e3a00db
Disallow-Recycled-Builds: test-failures
Reported-by: kernel test robot <lkp@intel.com>
Signed-off-by: Guenter Roeck <groeck@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/kernel/+/2743435
Reviewed-by: Pi-Hsun Shih <pihsun@chromium.org>