FIXUP: CHROMIUM: drivers: bluetooth: set up Qualcomm WCN399x for Android BQR commands
This patch fixes crrev.com/c/3141348 by adding a new config entry,
BT_HCIBTANDROID, to drivers/bluetooth/Kconfig, so that the new
btandroid module can be made and linked correctly when either
BT_HCIBTUSB or BT_HCIUART config entry is selected.

Context of the issue:
The bluetooth controller uses either the USB or UART transport.
The new btandroid module in question might be used with either
transport. However, USB and UART are independent from each other.
The independence should be maintained.

A new BT_HCIBTANDROID config entry is defined in this patch whose
value may be set by BT_HCIBTUSB and BT_HCIUART.

Without this patch, the following errors were reported by 0-day.

  hci_qca.c:(.text+0x329a): undefined reference to
      `btandroid_set_quality_report'

  btrtl.c:(.text+0xdda): undefined reference to
      `btandroid_set_quality_report'

Reported-by: kernel test robot <lkp@intel.com>

BUG=b:191730878
TEST=Build with various compile configs downloaded from 0-day
     (https://groups.google.com/g/cros-kernel-buildreports)
- config_parisc-buildonly-randconfig-r006-20210908
- config_riscv-randconfig-r012-20210908
There should be no undefined reference errors.

Also emerge in cros chroot and it should succeed.

Change-Id: I7e3d6c88ba093695dab10f665d2a104438e7154c
Signed-off-by: Joseph Hwang <josephsih@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/kernel/+/3153501
Reviewed-by: Guenter Roeck <groeck@chromium.org>