FIXUP: BACKPORT: dma-mapping: make support for dma ops optional
0-day reports:

arch/x86/pci/common.c:655:14: error: no member named 'dma_ops' in 'struct device'
                           pdev->dev.dma_ops = domain->dma_ops;

Above code was removed in the upstream kernel with commit dab0198413d2
("x86/PCI: Remove X86_DEV_DMA_OPS"). However, in v5.4.y, X86_DEV_DMA_OPS is
still selected by a couple of drivers and thus necessary. On the other side,
the dma_ops member in 'struct device' depends on DMA_OPS. Work around the
problem by selecting DMA_OPS from X86_DEV_DMA_OPS.

BUG=b:149115731
TEST=Run Camera app in lazor
TEST=Try https://appr.tc/?debug=loopback&vsc=vp8

Change-Id: I246451a6cd8445019cf3a4376c513a41f9654fc8
Disallow-Recycled-Builds: test-failures
Signed-off-by: Guenter Roeck <groeck@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/kernel/+/2836605
Reviewed-by: Douglas Anderson <dianders@chromium.org>
Reviewed-by: Ricardo Ribalda <ribalda@chromium.org>