FIXUP: UPSTREAM: misc: rtsx: Fix power down flow
0-day reports:

drivers/misc/cardreader/rtsx_pcr.c:1108:13: error:
	'rtsx_base_force_power_down' defined but not used

The function was added outside #ifdef CONFIG_PM but is only used
from inside.

BUG=b:175338107
TEST=chromeos-kernel-5_4

Change-Id: I1cbeb21085c3d18815d99f068e3591d27a7b9929
Disallow-Recycled-Builds: test-failures
Reported-by: kernel test robot <lkp@intel.com>
Signed-off-by: Guenter Roeck <groeck@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/kernel/+/2911127
Reviewed-by: Zhuohao Lee <zhuohao@chromium.org>
Reviewed-by: Alex Levin <levinale@google.com>