UPSTREAM: Bluetooth: btusb: fix excessive stack usage
Enlarging the size of 'struct btmtk_hci_wmt_cmd' makes it no longer
fit on the kernel stack, as seen from this compiler warning:

drivers/bluetooth/btusb.c:3365:12: error: stack frame size of 1036 bytes in function 'btusb_mtk_hci_wmt_sync' [-Werror,-Wframe-larger-than=]

Change the function to dynamically allocate the buffer instead.
As there are other sleeping functions called from the same location,
using GFP_KERNEL should be fine here, and the runtime overhead should
not matter as this is rarely called.

Unfortunately, I could not figure out why the message size is
increased in the previous patch. Using dynamic allocation means
any size is possible now, but there is still a range check that
limits the total size (including the five-byte header) to 255
bytes, so whatever was intended there is now undone.

BUG=b:178754244
TEST=build and boot on asurada

(cherry picked from commit 10888140f09c3472146dc206accd0cfa051d0ed4)

Fixes: 48c13301e6ba ("Bluetooth: btusb: Fine-tune mt7663 mechanism.")
Signed-off-by: Sean Wang <objelf@gmail.com>
Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Signed-off-by: Marcel Holtmann <marcel@holtmann.org>
(cherry picked from commit 10888140f09c3472146dc206accd0cfa051d0ed4)
Signed-off-by: Mark-YW Chen <mark-yw.chen@mediatek.corp-partner.google.com>
Change-Id: Ic0ec891d4310b3fe4c4b850b26241881727b1d4a
(cherry picked from commit a187571c5b22679c0222c512fd1d534a982bbc60)
Signed-off-by: Mark-YW Chen <mark-yw.chen@mediatek.corp-partner.google.com>
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/kernel/+/2773089
Reviewed-by: Sean Paul <seanpaul@chromium.org>
Reviewed-by: Claire Chang <tientzu@chromium.org>
Tested-by: Claire Chang <tientzu@chromium.org>
Commit-Queue: Yen-lin Lai <yenlinlai@chromium.org>