FIXUP: CHROMIUM: drm/i915: Disable boost and waitboost
gcc fails to build if -Werror is enabled.

drivers/gpu/drm/i915/intel_pm.c: In function 'gen6_rps_boost':
drivers/gpu/drm/i915/intel_pm.c:6650:16: error:
	unused variable 'flags' [-Werror=unused-variable]

Note: I would normally use __maybe_unused to tag possibly unused
variables. In this case, however, the CL introducing the problem
is a hack marked as temporary fix, thus I used the same kind of hack.

BUG=b:130638275
TEST=Compile with USE=-clang

Change-Id: I84e7c57b0df1cc822856977432b54760ab773d14
Signed-off-by: Guenter Roeck <groeck@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/1644068
Commit-Ready: ChromeOS CL Exonerator Bot <chromiumos-cl-exonerator@appspot.gserviceaccount.com>
Legacy-Commit-Queue: Commit Bot <commit-bot@chromium.org>
Reviewed-by: Stéphane Marchesin <marcheu@chromium.org>