FIXUP: FROMLIST: drm/msm/dp: add displayPort driver support
0-day reports:

In file included from drivers/gpu/drm/msm/dp/dp_pll.c:
drivers/gpu/drm/msm/dp/dp_pll_private.h:101:5: warning:
	no previous prototype for 'msm_dp_pll_10nm_init'

drivers/gpu/drm/msm/dp/dp_pll_10nm.c:358:6: error:
	redefinition of 'msm_dp_pll_10nm_deinit'

Problem is two-fold: First, dummy functions in include files
need to be declared "static inline" and, second, the 10nm code
must only be built if enabled.

BUG=b:148864048
TEST=Connect DP cable to type-c ports, see secondary display output, try

Change-Id: I3be7e45ee2f8f93e885efed9ba2496d29470ea87
Signed-off-by: Guenter Roeck <groeck@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/kernel/+/2337313
Reviewed-by: Stephen Boyd <swboyd@chromium.org>