FROMLIST: coresight: syscfg: fix compiler warnings
This fixes warnings with -Wimplicit-function-declaration, e.g.

drivers/hwtracing/coresight/coresight-syscfg.c:455:15: error:
implicit declaration of function 'kzalloc' [-Werror,
-Wimplicit-function-declaration]
        csdev_item = kzalloc(sizeof(struct cscfg_registered_csdev),
                             GFP_KERNEL);

Fixes: 85e2414c518a ("coresight: syscfg: Initial coresight system configuration")
Reviewed-by: Guenter Roeck <linux@roeck-us.net>
Signed-off-by: Jian Cai <jiancai@google.com>
(am from https://patchwork.kernel.org/patch/12465609/)
(also found at https://lore.kernel.org/r/20210830172820.2840433-1-jiancai@google.com)

BUG=b:185501434
TEST=CQ

Signed-off-by: Douglas Anderson <dianders@chromium.org>
Change-Id: If31a30326de3dc5c5b12062df6b27aacb17896e9
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/kernel/+/3149834
Reviewed-by: Sean Paul <seanpaul@chromium.org>
Reviewed-by: Manoj Gupta <manojgupta@chromium.org>