FIXUP: BACKPORT: dma-mapping: introduce DMA range map, supplanting dma_pfn_offset
0-day reports:

arch/x86/pci/sta2x11-fixup.c: In function 'sta2x11_map_ep':
arch/x86/pci/sta2x11-fixup.c:143:5: error:
	'struct device' has no member named 'dma_pfn_offset'

due to an incomplete backport.

BUG=b:187155802
TEST=Build and boot

Change-Id: I8e80cdd5aea7771a622d420949eba5d7ae82442e
Disallow-Recycled-Builds: test-failures
Signed-off-by: Guenter Roeck <groeck@google.com>
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/kernel/+/3271349
Commit-Queue: Tzung-Bi Shih <tzungbi@chromium.org>
Reviewed-by: Tzung-Bi Shih <tzungbi@chromium.org>
Tested-by: Tzung-Bi Shih <tzungbi@chromium.org>