UPSTREAM: remoteproc: qcom: Add missing slab.h
drivers/remoteproc/qcom_common.c: In function 'qcom_ssr_get_subsys':
drivers/remoteproc/qcom_common.c:210:9: error: implicit declaration of function 'kzalloc'; did you mean 'vzalloc'?
[-Werror=implicit-function-declaration]
  info = kzalloc(sizeof(*info), GFP_KERNEL);
         ^~~~~~~
         vzalloc

kzalloc() is declared in linux/slab.h, add include to fix build issue.

Tested-by: Alex Elder <elder@linaro.org>
Reported-by: Hulk Robot <hulkci@huawei.com>
Signed-off-by: Kefeng Wang <wangkefeng.wang@huawei.com>
Link: https://lore.kernel.org/r/20200713020003.134039-1-wangkefeng.wang@huawei.com
Signed-off-by: Bjorn Andersson <bjorn.andersson@linaro.org>
(cherry picked from commit 0cf17702d872128fc2bec79a9578b5cb00d54a11
 https://git.kernel.org/pub/scm/linux/kernel/git/andersson/remoteproc.git for-next)

BUG=b:74020136
TEST=Booted trogdor, modem call functional

Signed-off-by: Sujit Kautkar <sujitka@google.com>
Change-Id: Ia54a3224310dd1a4dba904c0d778f8d34422f2de
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/kernel/+/2330789
Tested-by: Sujit Kautkar <sujitka@chromium.org>
Commit-Queue: Douglas Anderson <dianders@chromium.org>
Reviewed-by: Douglas Anderson <dianders@chromium.org>
Reviewed-by: Sean Paul <seanpaul@chromium.org>