FIXUP: BACKPORT: dma-mapping: introduce DMA range map, supplanting dma_pfn_offset
0-day reports:

arch/sh/kernel/dma-coherent.c:41:44: error: 'struct device'
has no member named 'dma_pfn_offset'

Fixed compile error due to an incomplete backport.

BUG=b:187155802
TEST=Build and boot

Signed-off-by: Aashish Sharma <shraash@google.com>
Change-Id: I019f8e58a3d1026f86e5fe55594a049a5c3d84b4
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/kernel/+/3439826
Reviewed-by: Guenter Roeck <groeck@chromium.org>
Commit-Queue: Guenter Roeck <groeck@chromium.org>
Tested-by: Guenter Roeck <groeck@chromium.org>