UPSTREAM: cpufreq: intel_pstate: Fix static checker warning for epp variable
Fix warning for:
drivers/cpufreq/intel_pstate.c:731 store_energy_performance_preference()
error: uninitialized symbol 'epp'.

This warning is for a case, when energy_performance_preference attribute
matches pre defined strings. In this case the value of raw epp will not
be used to set EPP bits in MSR_HWP_REQUEST. So initializing with any
value is fine.

Reported-by: Dan Carpenter <dan.carpenter@oracle.com>
Signed-off-by: Srinivas Pandruvada <srinivas.pandruvada@linux.intel.com>
Acked-by: Viresh Kumar <viresh.kumar@linaro.org>
Signed-off-by: Rafael J. Wysocki <rafael.j.wysocki@intel.com>
(cherry picked from commit 3ff79754d7a2b27f6d2d56b3951fc9aa8080b063)

BUG=b:135666007
TEST=Verify the sysfs interface with different values

Signed-off-by: Ed Baker <edward.baker@intel.com>
Signed-off-by: Sumeet R Pawnikar <sumeet.r.pawnikar@intel.com>
Change-Id: I795fa5542dbc8be232419062adbd503f1ba9b316
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/kernel/+/2444966
Reviewed-by: Evan Green <evgreen@chromium.org>
Reviewed-by: Sean Paul <seanpaul@chromium.org>
Commit-Queue: Evan Green <evgreen@chromium.org>