CHROMIUM: x86/speculation: Fix coresched_select in tinyconfig
If tinyconfig is used, CONFIG_SYSFS is not set and the function is not
defined.

Fix:
undefined reference to `coresched_select'

BUG=b:193212307
TEST=make tinyconfig; make

Signed-off-by: Ricardo Ribalda <ribalda@chromium.org>
Fixes: abbb1dcb66bc ("FROMLIST: sched: Add a coresched command line option")
Change-Id: I7d7bd9b629c9779c76332d1656a302e8f79eb67d
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/kernel/+/3017376
Reviewed-by: Guenter Roeck <groeck@chromium.org>
Reviewed-by: Joel Fernandes <joelaf@google.com>