UPSTREAM: iommu/renesas: Fix unused-function warning
gcc warns because the only reference to ipmmu_find_group
is inside of an #ifdef:

drivers/iommu/ipmmu-vmsa.c:878:28: error: 'ipmmu_find_group' defined but not used [-Werror=unused-function]

Change the #ifdef to an equivalent IS_ENABLED().

Fixes: 6580c8a78424 ("iommu/renesas: Convert to probe/release_device() call-backs")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Reviewed-by: Simon Horman <horms@verge.net.au>
Link: https://lore.kernel.org/r/20200508220224.688985-1-arnd@arndb.de
Signed-off-by: Joerg Roedel <jroedel@suse.de>
(cherry picked from commit 2ba20b5a5b8f948d498f4b38ba910ff339e609ef)

BUG=b:232656957, b:227610040
TEST=Compile

Signed-off-by: Aashish Sharma <shraash@google.com>
Change-Id: Id4f8ec85419311fd58447ac296f3e9f1e1d6df91
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/kernel/+/3653365
Reviewed-by: Sean Paul <seanpaul@chromium.org>
Reviewed-by: Guenter Roeck <groeck@chromium.org>
Tested-by: Guenter Roeck <groeck@chromium.org>