FIXUP: CHROMIUM: drm/evdi: Find and attach to usb device with given usb path address
0-day reports:

evdi_drv.c:(.exit.text+0x28): undefined reference to `usb_unregister_notify'
evdi_drv.c:(.init.text+0x48): undefined reference to `usb_register_notify'
evdi_drv.c:(.text+0x5a0): undefined reference to `usb_for_each_dev'

evdi now depends on USB.

BUG=chromium:923165, b:172225747
TEST=Compile

Change-Id: I886b8e8eccb9bcd4a95ae3e366dd5a9981fb07f8
Disallow-Recycled-Builds: test-failures
Signed-off-by: Guenter Roeck <groeck@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/kernel/+/2710565
Reviewed-by: Łukasz Spintzyk <lukasz.spintzyk@synaptics.com>