FROMGIT: arm64: Fix build failure when HARDLOCKUP_DETECTOR_PERF is enabled
If HARDLOCKUP_DETECTOR_PERF is selected but HW_PERF_EVENTS is not, then
the associated watchdog driver will fail to link:

  |    aarch64-linux-ld: Unexpected GOT/PLT entries detected!
  |    aarch64-linux-ld: Unexpected run-time procedure linkages detected!
  |    aarch64-linux-ld: kernel/watchdog_hld.o: in function `hardlockup_detector_event_create':
  | >> watchdog_hld.c:(.text+0x68): undefined reference to `hw_nmi_get_sample_period

Change the Kconfig dependencies so that HAVE_PERF_EVENTS_NMI requires
the hardware PMU driver to be enabled, ensuring that the required
symbols are present.

Cc: Sumit Garg <sumit.garg@linaro.org>
Reported-by: kernel test robot <lkp@intel.com>
Link: https://lore.kernel.org/r/202012031509.4O5ZoWNI-lkp@intel.com
Fixes: 367c820ef080 ("arm64: Enable perf events based hard lockup detector")
Signed-off-by: Will Deacon <will@kernel.org>
(cherry picked from commit ce4b2c01781a24b0a04845f683feea44ade70503
 https://git.kernel.org/pub/scm/linux/kernel/git/will/linux.git for-next/perf)

BUG=b:172228850
TEST=trigger hardlockup on CPU, see stacktrace

Signed-off-by: Stephen Boyd <swboyd@chromium.org>
Change-Id: I60644b3c4eea3318f305d6b278a429a1a0293534
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/kernel/+/2576119
Reviewed-by: Sean Paul <seanpaul@chromium.org>
Reviewed-by: Douglas Anderson <dianders@chromium.org>