FIXUP: BACKPORT: FROMLIST: kvm/x86: virtual suspend time injection: Implement host side
0-day reports:

x86.c:(.text+0x24a75): undefined reference to `__udivdi3'

BUG=b:181617646
TEST=Build ARCH=i386 allyesconfig

Change-Id: Ib36d708ed42bf7f76f24247c594451d725a0eb2d
Disallow-Recycled-Builds: test-failures
Signed-off-by: Guenter Roeck <groeck@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/kernel/+/3308053
Reviewed-by: Hikaru Nishida <hikalium@chromium.org>
(cherry picked from commit 5ed42055e6f55708cf4062208ea5edb42968deec)
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/kernel/+/3308683
Commit-Queue: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>