UPSTREAM: xen-platform: Convert to generic power management
Convert xen-platform from the legacy PCI power management callbacks to the
generic operations.  This is one step towards removing support for the
legacy PCI callbacks.

The generic .resume_noirq() operation is called by pci_pm_resume_noirq() at
the same point the legacy PCI .resume_early() callback was, so this patch
should not change the xen-platform behavior.

Link: https://lore.kernel.org/r/20191101204558.210235-5-helgaas@kernel.org
Signed-off-by: Bjorn Helgaas <bhelgaas@google.com>
Acked-by: Rafael J. Wysocki <rafael.j.wysocki@intel.com>
Cc: Stefano Stabellini <sstabellini@kernel.org>
Cc: KarimAllah Ahmed <karahmed@amazon.de>
(cherry picked from commit 77b84bb306fd0d5d1d3a4bf1f2acf73dc971e372)

BUG=b:152064823
TEST=Compile with CONFIG_PM=y

0-day reports:

drivers/xen/platform-pci.c:176:3: error:
			'struct pci_driver' has no member named 'resume_early'
176 |  .resume_early =   platform_pci_resume,

Change-Id: Ia0522fc0e4e313685cf549de1d29a5ae871a31b3
Reported-by: kernel test robot <lkp@intel.com>
Signed-off-by: Guenter Roeck <groeck@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/kernel/+/2248243
Reviewed-by: Prashant Malani <pmalani@chromium.org>
Reviewed-by: Sean Paul <seanpaul@chromium.org>