FIXUP: FROMLIST: usb: dwc3: qcom: Configure wakeup interrupts and set genpd active wakeup flag
We should use a bitwise negation here instead of a logical one. Fixes
warnings like:

drivers/usb/dwc3/dwc3-qcom.c:409:20: error: converting the result of '<<' to a boolean always evaluates to true [-Werror,-Wtautological-constant-compare]
                genpd->flags &= !GENPD_FLAG_ACTIVE_WAKEUP;
                                 ^
include/linux/pm_domain.h:66:38: note: expanded from macro 'GENPD_FLAG_ACTIVE_WAKEUP'
                                     ^

BUG=b:147457041, b:145023729
TEST=on trogdor:
  PP3300_HUB consumes ~17 mW in S3
  clicking USB mouse during S3 wakes the DUT up

Signed-off-by: Stephen Boyd <swboyd@chromium.org>
Change-Id: Ibc1fdd6a81c47049e58b0ab35722344a3fcaf01f
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/kernel/+/2422699
Commit-Queue: Matthias Kaehlcke <mka@chromium.org>
Reviewed-by: Matthias Kaehlcke <mka@chromium.org>